CREATE TABLE SYSTEM_VERSION(
   ID   INT              	NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   VERSION VARCHAR (20)     NOT NULL
);



CREATE TABLE USERS(
   ID   INT              NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   LOGIN VARCHAR (20)    NOT NULL,
   NAME VARCHAR (60)     NOT NULL
);

INSERT INTO SYSTEM_VERSION (VERSION) VALUES('Version 1.0');